name: bw_region_init
channels:
  - conda-forge
  - defaults
  - cmutel
  - bsteubing
dependencies:
  - bw2analyzer
  - seaborn
  - bw2data
  - pyproj
  - matplotlib
  - brightway2
  - shapely
  - pandas
  - bw2io
  - notebook
  - beautifulsoup4
  - requests
  - statsmodels
  - scipy
  - python=3.11
  - cartopy
  - bw2parameters
  - pvlib
  - jupyterlab
  - gurobi=12.0.3
  - premise
  - xarray
  - geopandas
  - rasterio
  - pycountry
  - pip
  - bw2calc
  - scikit-learn
  - ipykernel
  - rioxarray
  - lxml
  - numpy
  - ipywidgets
  - gdal
  - tabulate
  - pyogrio
  - xlrd
  - tqdm
  - dask
  - ecoinvent_interface=3.1
  - pint
  - country_converter
  - folium
  - python-dateutil
  - pyyaml
  - constructive_geometries
  - jupyterlab_server
  - jupyter_server
  - openpyxl
  - fiona
  - jupyterlab_pygments
  - pytest
  - xlsxwriter
  - botocore
  - boto3
  - bw_migrations
  - pip:
      - lightgbm==4.6.0
      - shap==0.51.0
